# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wapps < Formula
  desc "wapps umbrella CLI for infra-tofu monorepo"
  homepage "https://github.com/wappsdev/wapps-cli"
  version "0.18.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wappsdev/wapps-cli/releases/download/v0.18.0/wapps_0.18.0_Darwin_x86_64.tar.gz"
      sha256 "049e01642983f72c322b9f843d0ae001e6df064388736572325cfec22b64b442"

      define_method(:install) do
        bin.install "wapps"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wappsdev/wapps-cli/releases/download/v0.18.0/wapps_0.18.0_Darwin_arm64.tar.gz"
      sha256 "15c181f71ea15dbc813abc6cdb806148bc8b7628ba84e58890b7b8830f6bfa71"

      define_method(:install) do
        bin.install "wapps"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wappsdev/wapps-cli/releases/download/v0.18.0/wapps_0.18.0_Linux_x86_64.tar.gz"
      sha256 "8472bad473da561d2c6e4160e3ddd103fcc47c74fc15a0ff3815a2404dfeba0b"
      define_method(:install) do
        bin.install "wapps"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wappsdev/wapps-cli/releases/download/v0.18.0/wapps_0.18.0_Linux_arm64.tar.gz"
      sha256 "d60e19347f49ce537b9ed703d788b194f79cfac7dc6f03b796eb6294bb684a12"
      define_method(:install) do
        bin.install "wapps"
      end
    end
  end

  def caveats
    <<~EOS
      Enable the AI-safe "wapps-secrets" skill so coding agents (Claude Code,
      Cursor, Aider) use apply-only secret commands and never read your .env:

        wapps skill install                 # user-wide (~/.claude/skills) — recommended
        wapps skill install --local --copy  # committable copy in the current repo

      After a future `brew upgrade wapps`, the skill auto-refreshes on the next
      `wapps` run — no need to re-install.
    EOS
  end

  test do
    assert_match "wapps", shell_output("#{bin}/wapps --help")
  end
end
